name: Build Corne rev4.1 (Naginata)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build QMK firmware
        uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev4_1/standard
          keymap: naginata_v13
          output-dir: qmk-output

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: corne-rev4_1-naginata
          path: qmk-output
